# BEGIN
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
# END
